docsrc/migration.rst

Simplified and cut down on the new api examples to try to directly 'match' what the old code examples were doing

Simplified examples for migration documentation

---

docsrc/docextract_settings.rst

Pretty minor but important update with a number of changes to the DocumentExtraction settings page. Basically went through many of the settings and verified that they worked as advertised and adjusted the docs to match.

Fixing errors in DocumentExtraction settings

---

indico/queries/jobs.py

Think we need something to avoid abusing our remote servers.

Request interval setting to avoid server abuse

---

indico/__init__.py
indico/_version.py
setup.py

Option 5 from the python packaging guide for single-sourcing version.  https://packaging.python.org/guides/single-sourcing-package-version/.

ADD:get version metadata from setup.py

---

indico/queries/model_groups.py
tests/integration/queries/test_model_group.py

Update client test to call predict with threshold.

ADD:predict options and test

---

examples/get-training-model-progress.py
examples/graphql.py
examples/single-doc-extraction.py
examples/train-classification-model.py

Simplified the examples in the documentation- removed unnecessary imports, functions and other executables to instead focus on client library use.

Simplified the examples in the documentation

---

docsrc/workflow-intro.rst

Small changes to workflow text in docs

explicitly mention OCR and fix location on how to pass docs in app

---

docsrc/graphql_queries.rst
docsrc/index.rst

Added a page in the docs with several common graphql queries and the variables needed to use the

added doc page for common graphql queries

---

indico/queries/submission.py
indico/queries/workflow.py
indico/types/submission.py
tests/integration/queries/test_workflow.py

Depends on https://github.com/IndicoDataSolutions/fog/pull/246
We now support getting back full submission objects when we create workflow submissions
Created as a new fn since the return type is different from the original WorkflowSubmission query

[DEV-5183] Astha/workflow sub obj

---

examples/submission.py
indico/client/request.py
indico/queries/workflow.py
tests/integration/conftest.py
tests/integration/data/datasets.py
tests/integration/queries/test_workflow.py

Depends on:
- https://github.com/IndicoDataSolutions/fog/pull/256

[DEV-5365] ADD: url support for WorkflowSubmission

---

indico/queries/workflow.py

I was testing with Detailed - forgot to run the tests for the regular query

FIX: query str

---

examples/submission.py
indico/queries/submission.py

```
Waited submissions [(11441, 'PENDING_AUTO_REVIEW', '/storage/submission/1632/11441/submission_11441_result.json'), (11442, 'COMPLETE', '/storage/submission/1632/11442/submission_11442_result.json')]
Changes {'invoices price range q450 model': {'confidence': {'more_than_1000': 0.7106317558145944, '500_to_1000': 0.2126695627565185, 'less_than_500': 0.07881872964357038}, 'label': ['more_than_1000'], 'accepted': True}, 'invoices_extraction_less_than_500': None, 'invoices_extraction_more_than_1000': [{'start': 0, 'end': 18, 'label': 'Vendor', 'text': 'InsureTech Connect', 'confidence': {'<PAD>': 0.000531987810973078, 'Vendor': 0.9990828037261963, 'Line Item': 0.00023377692559733987, 'Line Item Value': 9.400565613759682e-05, 'Total': 1.2766715371981263e-05, 'Invoice Number': …
```

[DEV-5350] ADD: submission auto review queries

---

indico/queries/workflow.py
tests/integration/queries/test_workflow.py

DEV-5666 add auto_review_enabled to GetWorkflow and ListWorkflow response

---

indico/__init__.py
indico/_version.py

somehow removed part of versioneer's code

fix tagging

---

README.md
docs/_sources/intro.rst.txt
docs/intro.html
docsrc/intro.rst

update python version info from 3.6+ -> 3.6, 3.7, 3.8

updated version information

---

indico/filters/__init__.py

Adds status to doc report filter

[CAT-152] add status into filter

---

indico/queries/document_report.py
indico/types/document_report.py
tests/integration/queries/test_document_report.py

Adding num pages and file size to doc report. This is critical for customers to bill correctly.

adding two attributes to doc reports

---

indico/filters/__init__.py

Update __init__.py typo in comment

---

indico/queries/document_report.py
indico/types/document_report.py
tests/integration/queries/test_document_report.py

Adding all submissions option to the client
Adding submission id to the DocumentReport object (instead of just the input file as it should be at the document report level) 
- [- ] Hard-to-understand areas have been commented (my code is self documenting)

[CAT-187] Add all submissions option and submission id to document report

---

indico/queries/datasets.py
indico/types/dataset.py
tests/integration/queries/test_dataset.py

[CAT-164] pluggable ocr dataset options

---

indico/config/config.py
tests/unit/client/test_config.py

Allow setting API token using environment variables
- [] Documentation has been updated

Add ability to set API token with env variables

---

indico/queries/workflow.py
indico/types/base.py
indico/types/workflow.py
tests/integration/queries/test_workflow.py
tests/unit/types/test_base_type.py

Add createdBy and createdAt to workflow object
- [ X] Jira story/task is put into PR title
- [X ] Code has been self-reviewed
- [ X] Hard-to-understand areas have been commented
- [ X] My changes generate no new warnings
- [ X] Unit tests have been added for base functionality and known edge cases

[CAT-207][CAT-197] Add workflow audit information to workflow object in client

---

indico/queries/workflow.py

record submission needs to be removed

---

tox.ini

test 38 and 39

---

examples/submission.py
examples/workflow.py

updating submission examples to be more realistic

updating submission examples to be more realistic

---

indico/queries/datasets.py

Permit specifying OCR settings from CreateDataset

DEV-9352 FIX: issue with ocr config pass through

---

indico/queries/workflow.py
indico/queries/workflow_components.py
indico/types/model_group.py
indico/types/workflow.py

add 
- ClassNames to modelGroup attribute in Workflows
- add filters attribute to workflowComponentLinks
- make labels an optional kwarg to AddLinkClassificationComponent
- Add after_link_id to AddModelGroupComponent

[CAT-322] and 320 and 321

---

indico/queries/storage.py

Update indico url scheme for blob

feat: update storage url scheme

---

.gitignore
Dockerfile
codeship-services.yml
indico/config/config.py
indico/queries/__init__.py
indico/queries/integration.py
indico/types/__init__.py
indico/types/base.py
indico/types/integration.py
tests/integration/conftest.py
tests/integration/queries/test_integration.py
tests/integration/queries/test_model_group.py

Also updated the name of the dev cluster

[CAT-501] ADD: functionality for adding exchange integration to a workflow

---

README.md

Add instructions for running tests.

[CAT-511] add instructions for running tests

---

indico/types/dataset.py

ADD: readapi-v2 to enum

---

indico/queries/model_groups/model_groups.py

[CAT-433] Deprecate ModelLoad

---

tests/integration/data/AirlineComplaints.csv
tests/integration/queries/test_dataset.py

[CAT-646] Fix skipped integration tests

---

indico/queries/questionnaire.py
indico/types/questionnaire.py
tests/integration/queries/test_questionnaire.py

* Update GetQuestionnaire query
* Update Questionnaire type
* Update integration test for `AddLabels`

[CAT-657] update structure of labels in addLabels integration test

---

tests/integration/queries/test_workflow_component.py

This adds positive and negative test cases for filtered classes, the negative being an invalid syntax.

[CAT-659] improve test for filtered classes

---

examples/submission.py

Lauri messaged me about a bug in this example earlier today. This PR fixes the typo.

update submission example

---

docs/index.html

add banner

---

README.md
docs/_sources/graphql_queries.rst.txt
docs/_sources/intro.rst.txt
docs/_sources/workflow-intro.rst.txt
docs/config.html
docs/document-report-ex.html
docs/graphql-ex.html
docs/graphql_queries.html
docs/image-dataset-ex.html
docs/intro.html
docs/submission-ex.html
docs/train-predict-ex.html
docs/training-progress.html
docs/user-metrics-ex.html
docs/workflow-ex.html
docs/workflow-metrics-ex.html
docsrc/env-vars.csv
examples/aio_client.py
examples/create-download-export.py
examples/create-image-dataset.py
examples/custom_client.py
examples/get-document-report.py
examples/get-training-model-progress.py
examples/get-user-metrics.py
examples/get-workflow-metrics.py
examples/graphql.py
examples/submission.py
examples/train-classification-model.py
examples/workflow.py

Update all references to `app.indico.io` to `try.indico.io` since app is now deprecated

update app to try

---

indico/queries/submission.py
tests/integration/queries/test_workflow.py

add support for v3 result in auto review

---

indico/queries/workflow.py

[DEV-11433] use uploadbatched instead of upload document

---

indico/queries/questionnaire.py
tests/integration/queries/test_workflow.py

Update GetQuestionnaire as a RequestChain to wait on COMPLETE questionnaire status

[DEV-11498] update getquestionnaire

---

indico/queries/submission.py
indico/types/submission.py
tests/integration/queries/test_submission.py

draft PR but nice to include changes here as it's part of the get reviews API
We don't include changes by default due to size

GetReviews with changes

---

indico/queries/document_report.py
indico/queries/submission.py
indico/types/document_report.py
tests/integration/queries/test_workflow.py

deleted is deprecated on fog so converting to filesDeleted

[DEV-11535] deprecate deleted -> filesDeleted for Submission

---

Dockerfile
tox.Dockerfile

fix: change dockerfile

---

indico/queries/model_import.py
indico/queries/workflow_components.py

fix: [DEV-12677]: Static Model fixes

---

.harness/publish_python_sdk.yaml

trying bash for multiline commit messages 🤷

fix: Pipeline bash

---

indico/client/client.py
indico/filters/__init__.py
indico/http/client.py
indico/http/serialization.py
indico/queries/datasets.py
indico/queries/document_report.py
indico/queries/export.py
indico/queries/gallery.py
indico/queries/model_import.py

straggling typing errors from rebase

fix: typing from rebase

---

indico/client/client.py
indico/client/request.py
indico/queries/gallery.py
indico/types/component_blueprint.py
tests/integration/queries/test_gallery.py

[DEV-13086] Gallery SDK update

---

indico/queries/gallery.py
indico/queries/workflow.py
indico/types/workflow.py
tests/integration/queries/test_gallery.py

fix: [DEV-13100] add dataset_id to Workflow type

---

indico/queries/workflow_components.py
indico/types/base.py
indico/types/model_group.py

fix: [DEV-13700] update NewLabelsetArgs to accept fieldData

---

indico/client/request.py
indico/filters/__init__.py
indico/queries/example.py
indico/queries/questionnaire.py
indico/types/questionnaire.py
tests/integration/queries/test_questionnaire.py

feat: [DEV-12997]: Bundles
