docsrc/docextract_settings.rst

Added the import statements to the main example (this had confused me initially), made language more consistent, added '(default)' to kwarg values where I knew them, removed deprecated features (n_threads, etc.)

Updating DocumentExtraction docs

---

README.md
docsrc/docextract_settings.rst
indico/queries/documents.py

Updated the DocumentExtraction docs and docstring to include "ondocument" and (pending) "standard" preset configurations. For now, changed default preset to "legacy" (should change to "standard" when it's ready) and clarified that "simple" is only for native PDFs. Fixed git clone readme snippet to clone this repo.

updated DocumentExtraction docs to include ondocument and standard presets

---

docsrc/docextract_settings.rst

Added more information on what the preset configurations do and what python objects they return, removed a reference to the api token being recognized (without an explicit path) in the working directory, added some additional details/context for a couple of kwargs.

Updated DocumentExtraction documentation for preset configurations

---

indico/queries/model_groups.py

If you currently use an invalid modelgroup ID with this call:
`model_id = client.call(GetModelGroup(25147))`
You get:
```
~/Desktop/jupyter_kernels/new_client/venv/lib/python3.7/site-packages/indico/queries/model_groups.py in process_response(self, response)
44     def process_response(self, response):
45         mg = ModelGroup(
---> 46             **super().process_response(response)["modelGroups"]["modelGroups"][0]
47         )
48         return mg
IndexError: list index out of range
```
Improving this error to let the user know that the ModelGroup hasn't been found and to check the ID they're using.

Improving error message when an invalid model group is called

---

indico/queries/storage.py

When a user doesn't check if a Job.status is 'FAILURE' they are most likely going to run into a KeyError 'url'  when calling RetrieveStorageObject (most often when doing OCR w/ DocumentExtraction). Our Chatham clients (as well as myself and Andrew) have all run into this error and been initially stuck as to what the problem might be.
Updated with two lines to check if 'url' is in the storage object dictionary and, if not, raise an error for the user to check the job result/status and suggest that it could be a credential/specification issue. Even though this could be avoided in a user's own code, it has been a common problem already and seems that, for now, an easy fix with a better error message might save clients some frustration.

catching most common object retrieval error 

---

README.md

There were a few errors in the README code samples that made it impossible to run the code (several errors in the imports, a method instead of an attribute, etc.)

fixing errors in the readme code samples

---

setup.py

Pinning python version may be annoying for people on python 1.0 locally. We only brought in python to be able to read a dataframe.

FIX:dont require exact python version

---

docsrc/model_predictions.rst

The code snippet in the docs for predictions included 'return' without any function. I also added in the imports as well as creating the client in case someone navigates to this page first

fixing code snippet error

---

indico/client/client.py

Currently, many of our clients need to set verify_ssl=False in the their configuration (WR Berkley for example) like:
```
config = IndicoConfig(verify_ssl=False)
client = IndicoClient(config)
```
This leads to hundreds of warnings (depending on how the script is written) in the terminal like below that drown out all other print statements and look bad to the client: 
```
InsecureRequestWarning,
/home/scott/Desktop/wrberk/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'wrb-pilot.indico.domains'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```
This PR suppresses those warnings

suppress warnings when verify_ssl=False in config

---

indico/http/client.py
tests/integration/queries/test_document.py

Also requires https://github.com/IndicoDataSolutions/indico-deployment/pull/644
Basically if we see [foo.pdf, foo.pdf, bar.pdf], for us just temporarily, it becomes [foo.pdf, foo(2).pdf, bar.pdf]
Possibly we need to do this in other SDKs, not sure
tested on a feature cluster
Code:
```
files = [invoices[0], invoices[0], invoices[0], invoices[1]]
files_to_extract = client.call(
UploadDocument(files=files)
)
print(f"FILES TO EXTRACT ARE: {len(files_to_extract)}. Jobs: ", files_to_extract)
```
Response before:
```
FILES PASSED {'files': ['/home/astha/Downloads/samples/invoices/26199.pdf', '/home/astha/Downloads/samples/invoices/26199.pdf', '/home/astha/Downloads/samples/invoices/26199.pdf', '/home/astha/Downloads/samples/invoices/26265.pdf']}                                  
FILES PROCESSED …
```

[DEV-5197] FIX: allow multiple files of same name to be uploaded

---

indico/config/config.py
indico/http/client.py
tests/unit/client/test_client.py

Added ability to pass dictionary of requests.Sessions parameters to set 
Note: the only real change to tests/unit/client/test_client.py is the last test, all the other changes are just from applying black formatting.

added ability to pass session params from config

---

indico/queries/datasets.py
indico/queries/submission.py
indico/queries/workflow.py

Basically don't allow folks to pass in args where we'd prefer kwargs (to prevent any unexpected results)
Also something worth adding is an "Options" part to the docstring to distinguish between required args and optional ones. could change that up in this PR - or we can decide on some standard and I can clean it all up in a separate PR

FIX: require some args to be keyword-only

---

indico/queries/datasets.py
tests/integration/data/classification.csv
tests/integration/queries/test_dataset.py

After the `test_csv_incompat_columns` test was written, I had fixed fog to use the correct enum type so that file_type is returned as `CSV` instead of `csv` at which point this test was out of date.  The reason it hangs is because we call `ProcessCSV` with wait and the file never gets processed because we passed in an empty list of `datafile_ids`. So we keep polling for dataset file statuses and they never leave `DOWNLOADED` state. 
Separately, the logic for `CreateDataset` request chain wait was incorrect. It should wait on file statuses not on dataset status because we may not fail a dataset if there is failure processing a file. When a user attempts to process a datafile that is associated with a dataset it should end up in either PROCESSED or FAILED state. 
No platform bugs in both …

[DEV-5292]: FIX request chain, existing test, and add test

---

indico/types/base.py
tox.Dockerfile
tox.ini

some changes in 3.9 mean the way list types were previously detected no longer work, but this should fix the issue and work with older versions as well

fix 3.9 issue

---

indico/http/client.py
indico/queries/storage.py
indico/queries/workflow.py

This enables SDK users to manage their own file reading and upload to the backend by providing a map of filenames to  streams, so in addition to`files` on a `WorkflowSubmission`, you can add `io.BufferedIOBase` inheriting `streams` directly.
Modified WorkflowSubmission object to add optional streams
Modified Storage upload object to add optional streams
Modified client.py to handle the optional streams similar to files.
Please delete options that are not relevant.
A quick checklist of things that should be done before the code is opened to review by others on the team.
Delete any that are not applicable.

[CAT-102] byte stream support

---

examples/submission.py
indico/queries/document_report.py
indico/queries/submission.py
tests/integration/queries/test_workflow.py

Including the old changes from this PR when pagination was first added
https://github.com/IndicoDataSolutions/indico-client-python/pull/90/files
Includes a fix for the doc report pagination - which didn't add the `after` variable to the query to allow for pagination - after is used to indicate where the next page should start

[CAT-126] ADD: pagination to ListSubmissions

---

indico/errors.py
indico/http/client.py

Moved the error handling for 500 errors above the attempt to decode content so that an` IndicoDecodingError` doesn't get thrown before the server errors are checked.
Added a check for a 503 response code and throw an `IndicoHibernationError` if the retry-after header is set.

[CAT-171] & [CAT-168] Fix exception handling for hibernation and decoding

---

indico/filters/__init__.py
tests/unit/test_filters.py

- add default end date to document report filter, if start date is provided
- throw error if an end date is provided but the corresponding start date isn't

[CAT-232] FIX: Update Document Report Filter behavior

---

indico/types/dataset.py

Looking to improve error handling for `Dataset` base type. Raises an `IndicoInputError` vs a `StopIteration` error when name is not found for methods `labelset_by_name` and `datacolumn_by_name`. 
- Added conditions to `Dataset` methods to check if name is present. If not, raise `IndicoInputError`. 
- If labelset or datacolumn not found, listing available names for user.

Added error messaging for Dataset basetype methods

---

indico/queries/document_report.py
indico/types/document_report.py

`createdBy` and `deleted` are required as part of the weather station reporting, and they're exposed via the api but not the SDK. this PR adds them to the sdk call.

ADD: created_by and deleted fields to document report

---

indico/queries/document_report.py
indico/types/document_report.py
tests/integration/queries/test_document_report.py

Include the submission file id in the document report, so we can differentiate between different files with the same name

ADD id for sub file in doc report

---

tests/integration/data/datasets.py

This change makes it so the integration tests that work for 5.x also work for 6.0. Comparison between the two sets of test [here](https://docs.google.com/spreadsheets/d/1-TUeCZrj4ylJarPwRd5kRQwLD8XZt56dvmGyMo9oN8k/edit#gid=629986350)

[CAT-510] FIX: add output nodes to workflow created during integration tests

---

indico/http/client.py
indico/http/serialization.py
tests/integration/conftest.py

In 5.x, the storage object returned by Document Extraction has a content type of `application/x-gzip`, but in 6.0 the content type is `binary/octet-stream`.
Since we can't always tell by the content type if the response needs to be decompressed, check the request URL and decompress the response if need be.

[CAT-515] FIX: force decompress when deserializing if url ends in gz

---

indico/queries/questionnaire.py
tests/integration/data/datasets.py
tests/integration/queries/test_model_group.py
tests/integration/queries/test_questionnaire.py
tests/integration/queries/test_workflow.py
tests/integration/test_base_client.py

- fix typing in questionnaire so questionnaire tests pass
- update tests to expect latest submission result file version to be 3
- skip tests around indico not found error, since we don't support that anymore

fix typing for questionnaire calls and update tests

---

tests/integration/queries/test_document.py

The test for retrieving images from document extraction OCR output has been failing since 5.x. As of 5.x, the default OCR config no longer includes returning the image link. This PR updates the test to use the simple config, which does include image links.

[CAT-633] FIX: document extraction image test

---

indico/queries/model_groups/model_groups.py
indico/queries/questionnaire.py
tests/integration/conftest.py
tests/integration/data/datasets.py
tests/integration/queries/test_document.py
tests/integration/queries/test_document_report.py
tests/integration/queries/test_export.py
tests/integration/queries/test_integration.py
tests/integration/queries/test_model_group.py
tests/integration/queries/test_questionnaire.py
tests/integration/queries/test_user_metrics.py
tests/integration/queries/test_workflow.py
tests/integration/queries/test_workflow_component.py
tests/integration/queries/test_workflow_metrics.py
tests/integration/test_base_client.py

- Fix issues with integration test fixtures
- Increase timeouts when waiting for submissions to complete, to increase the chance of those tests passing
- Expect submission filenames to include full path
- Reformat with black
NOTE: `tests/integration/queries/test_document.py::test_document_extraction_images` and `tests/integration/queries/test_questionnaire.py::test_add_labels` are still failing. Both of these tests require changes to the SDK itself to pass, so I'll create tickets and we can prioritize them separately.

[CAT-644] FIX: integration tests

---

indico/http/client.py

This fixes a bug where 5XX response status codes raise `TypeError: IndicoRequestError.__init__() missing 1 required positional argument: 'error'` instead of an instance of `IndicoRequestError`.
Also includes the response content bytes as extras to aid debugging.

Add missing required `error` argument to `IndicoRequestError()`

---

docs.Dockerfile
docsrc/conf.py
scripts/build_docs.sh

- Add separate dockerfile specifically for building docs
- Modify sphinx config to generate markdown instead of HTML
- Use the `sphinx-markdown-builder`extension for markdown generation
- Update copyright year and version number in sphinx config

[CAT-803] Add dockerfile for container that generates markdown docs

---

examples/aio_client.py

Received feedback to remove `create()` and `cleanup()` and include only async context manager. 
Context manager uses `create()` and `cleanup()` internally, so opted to just update examples instead of moving the methods into `__aenter__` and `__aexit__` respectively

[DEV-11455] update async client example

---

examples/aio_client.py
indico/client/client.py
indico/client/request.py
indico/queries/datasets.py
indico/queries/export.py
indico/queries/jobs.py
indico/queries/model_groups/model_groups.py
indico/queries/questionnaire.py
indico/queries/submission.py
indico/queries/workflow.py

Request chains with a wait argument use time.sleep() internally, rather than yielding a delay to the client to sleep synchronously or asynchronously as appropriate. Moved sleeping to client and making all wait calls yield a float or integer denoting sleep time

[DEV-11456] make request chains wait appropriately for sync/async calls

---

indico/http/client.py
tests/unit/client/test_aiohttp_client.py

AsyncIndicoClient _handle_files context manager incorrectly updated the file args for the aiohttp call. Instead of using the path.name for the file to upload we used path.stem, resulting in the file extension being lost
streams correctly captured the filename, as well as the sync _handles_file manager

[DEV-11730]: fix async client handle files

---

indico/http/serialization.py
indico/queries/datasets.py
indico/queries/export.py
setup.py
tox.ini

Make large dependencies like Numpy and Pandas optional to reduce the base install size of the client. These are required by only a handful of uncommon calls, yet represent 75% of the install size. This will better support customers who use the client in AWS Lambdas where they're limited to 250Mb.
```
[michael@macbook indico-client-python]$ du -hd 1 . | grep venv
37M    ./venv-base
146M    ./venv-all
```
- Removed `pillow` as it appears to be unneeded.
- Made `msgpack` and `numpy` optional as they are only used for specific deserialization functions.
- Available via the `indico-client[deserialization]` or `indico-client[all]` extras.
- Made `pandas` optional as it is only used for creating image datasets and retrieving exports.
- Available via the `indico-client[datasets]`, …

[DEV-11651] Reduce base install size by making Msgpack, Numpy, and Pandas optional dependencies

---

README.md
indico/http/serialization.py
tox.Dockerfile
tox.ini

Python 3.13 removed the deprecated `cgi` module. This PR replaces usage of `cgi.parse_header()` with `email.message.EmailMessage` per the [release notes](https://docs.python.org/3/whatsnew/3.13.html#pep-594-remove-dead-batteries-from-the-standard-library) to make it 3.13-compatible.
(Also removes the unconditional import of `msgpack` which I missed in #314 🙃)

[DEV-12949] Python 3.13 Compatibility

---

indico/http/serialization.py
indico/queries/model_export.py
indico/queries/model_import.py
indico/queries/submission.py
indico/queries/workflow_components.py

Fix regression in support for Python <3.10

[DEV-13128] fix: bad runtime typing
